### ISSUE TITLE
errors when run "python3 setup.py"

### ISSUE THREAD

**Issue by YaLunDong** [Huelse/pyseal#2]
Hello,
    when I run "python3 setup.py", it returns an error as follows:
 
![image](https://user-images.githubusercontent.com/23722139/68025392-93deae00-fce7-11e9-8fdb-06a1e83c5d39.png)
I have followed your instructions correctly, could you please give me some help?
Thanks

**Comment by Huelse** [comment]
Your SEAL's version is not right. You should use the SEAL3.3 in this res

**Comment by YaLunDong** [comment]
> Your SEAL's version is not right. You should use the SEAL3.3 in this res

Thank you
